server:
  port: 8090

spring:
  datasource:
    username: root
    password: yzp230mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_aop_log?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowMultiQueries=true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

logging:
  level:
    com.yzp.log: debug
